### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by DiexMi** [hy418618674/PokemonsStatus#1]
1、谷歌验证码的网址最好加上https://防止不跳转
2、在客户端上登陆时，客户端的验证码并没有被复制到网页上，粘贴板里也没有，可能是我多个谷歌账户的原因

**Comment by huangyiyang89** [comment]
http 少了个s。已经修改。

谷歌登录保证configs/googleauth.ini 是空的，才会复制验证码，否则会尝试用该配置文件内的内容来获得accesstoken。

**Comment by DiexMi** [comment]
最新的版本问题依旧啊……验证码依然不会复制，我是win10x64专业版的，给过管理员权限也试过兼容到老系统，也不好使，就是不出验证码，现在网页版也是，时不时好使一下，然后就一直没验证码，我是用xx-net翻得墙，改hosts骑的墙，两者都分别试过，浏览器也换过，依然没有验证码……

**Comment by blast526** [comment]
网页的获取验证码没反应，PC端获取验证码崩溃

**Comment by huangyiyang89** [comment]
谷歌登录现在有点问题，正在解决

**Comment by DiexMi** [comment]
新版客户端非常好用，谢谢

**Comment by huangyiyang89** [comment]
感谢。
